In [1]:
import pickle

In [5]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [6]:
X

array([[[168, 166, 166, ..., 115, 109, 103],
        [167, 166, 166, ..., 115, 109, 104],
        [167, 167, 167, ..., 116, 110, 104],
        ...,
        [176, 180, 185, ..., 101, 101, 101],
        [175, 172, 172, ..., 100, 101, 101],
        [178, 180, 187, ..., 101, 100, 101]],

       [[ 89,  91,  93, ...,  60,  59,  54],
        [ 89,  92,  96, ...,  58,  56,  56],
        [ 89,  92,  96, ...,  55,  54,  58],
        ...,
        [110, 108, 101, ..., 125, 120, 112],
        [101, 100, 108, ..., 131, 121, 118],
        [101, 100, 102, ..., 172, 121, 129]],

       [[ 57,  64,  74, ...,  70,  69,  55],
        [ 74,  76,  85, ...,  71,  74,  66],
        [ 79,  87,  90, ...,  82,  68,  69],
        ...,
        [173, 153, 160, ..., 220, 215, 209],
        [166, 162, 150, ..., 212, 210, 201],
        [172, 158, 142, ..., 212, 208, 197]],

       ...,

       [[ 60,  64,  58, ..., 155, 154, 150],
        [ 61,  63,  62, ..., 154, 156, 152],
        [ 64,  65,  61, ..., 155, 159, 155

In [7]:
y

array([0, 1, 0, ..., 0, 1, 1])

In [8]:
X = X/255

In [9]:
X

array([[[0.65882353, 0.65098039, 0.65098039, ..., 0.45098039,
         0.42745098, 0.40392157],
        [0.65490196, 0.65098039, 0.65098039, ..., 0.45098039,
         0.42745098, 0.40784314],
        [0.65490196, 0.65490196, 0.65490196, ..., 0.45490196,
         0.43137255, 0.40784314],
        ...,
        [0.69019608, 0.70588235, 0.7254902 , ..., 0.39607843,
         0.39607843, 0.39607843],
        [0.68627451, 0.6745098 , 0.6745098 , ..., 0.39215686,
         0.39607843, 0.39607843],
        [0.69803922, 0.70588235, 0.73333333, ..., 0.39607843,
         0.39215686, 0.39607843]],

       [[0.34901961, 0.35686275, 0.36470588, ..., 0.23529412,
         0.23137255, 0.21176471],
        [0.34901961, 0.36078431, 0.37647059, ..., 0.22745098,
         0.21960784, 0.21960784],
        [0.34901961, 0.36078431, 0.37647059, ..., 0.21568627,
         0.21176471, 0.22745098],
        ...,
        [0.43137255, 0.42352941, 0.39607843, ..., 0.49019608,
         0.47058824, 0.43921569],
        [0.3

In [18]:
X = X.reshape(-1, 60, 60, 1)

In [19]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [20]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [21]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [26]:
model.fit(X, y, epochs=5, validation_split=0.1)

Train on 20700 samples, validate on 2300 samples
Epoch 1/5
20700/20700 [==============================] - 114s 5ms/step - loss: 0.5393 - accuracy: 0.7279 - val_loss: 0.4937 - val_accuracy: 0.7730
Epoch 2/5
20700/20700 [==============================] - 113s 5ms/step - loss: 0.4644 - accuracy: 0.7780 - val_loss: 0.4560 - val_accuracy: 0.7917
Epoch 3/5
20700/20700 [==============================] - 113s 5ms/step - loss: 0.4062 - accuracy: 0.8120 - val_loss: 0.4498 - val_accuracy: 0.7874
Epoch 4/5
20700/20700 [==============================] - 113s 5ms/step - loss: 0.3390 - accuracy: 0.8523 - val_loss: 0.4379 - val_accuracy: 0.7987
Epoch 5/5
20700/20700 [==============================] - 114s 6ms/step - loss: 0.2541 - accuracy: 0.8936 - val_loss: 0.4907 - val_accuracy: 0.8017


In [23]:
X.shape

(23000, 60, 60, 1)

In [27]:
import time

time.time()

1581428129.5990093

In [28]:
type(1581428129.5990093)

float